First Upload
EarthSciML/GasChemMTK.jl pull request #2
Opened 2021-12-09 16:09 UTC by jialinl6

2021-12-09 20:36 UTC, ctessum commented
You can review the contributor license agreement above, and if you agree with it, just type "I have reviewed and hereby sign the CLA" in the comment box below. It just basically just says that you agree that we can release your work as open source software.

2021-12-09 21:04 UTC, ctessum requested changes
Looking good! I added a couple of comments/suggestions.

2021-12-09 21:04 UTC, ctessum commented on src/SuperFast.jl
> +### Building Model
Could you add some background information here, such as what this algorithm does, what paper(s) it comes from, and any information other people might need to understand what you did here or use it in their own work?

2021-12-09 21:04 UTC, ctessum commented
Also, you can review the contributor license agreement above, and if you agree with it, just type "I have reviewed and hereby sign the CLA" in the comment box below. It just basically just says that you agree that we can release your work as open source software.

2021-12-12 21:20 UTC, jialinl6 commented
> I have reviewed and hereby sign the CLA

2021-12-13 00:44 UTC, jialinl6 commented on src/SuperFast.jl
> +@parameters r1 r2 r3 r6 r7 r9 r11 r12 r13a r13b r14 r15 r17 r21a r21c r22 rr1 rr2 rr3 rr4 rr5 rr6  r4 r5 r10 t
Sure, I just added the units

2021-12-13 00:45 UTC, jialinl6 commented on src/SuperFast.jl
> +### Building Model
Thank you for the advice! I just added a brief description at the beginning.

2021-12-13 00:55 UTC, jialinl6 commented
recheck

2021-12-13 14:36 UTC, ctessum commented
I have reviewed and hereby sign the CLA

2021-12-13 14:36 UTC, ctessum commented
recheck

2021-12-13 14:40 UTC, ctessum approved these changes
Looks good, thanks!

2021-12-13 14:41 UTC, merged